# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.srcs/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0.xci
# IP: The module: 'system_sys_dlmb_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_dlmb_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.srcs/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0.xci
# IP: The module: 'system_sys_dlmb_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_sys_dlmb_cntlr_0/system_sys_dlmb_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_dlmb_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
