# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.srcs/sources_1/ip/ad9361_fifo/ad9361_fifo.xci
# IP: The module: 'ad9361_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/ad9361_fifo/ad9361_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9361_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/ad9361_fifo/ad9361_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9361_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/ad9361_fifo/ad9361_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9361_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.srcs/sources_1/ip/ad9361_fifo/ad9361_fifo.xci
# IP: The module: 'ad9361_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/ad9361_fifo/ad9361_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9361_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/ad9361_fifo/ad9361_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9361_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/ad9361_fifo/ad9361_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9361_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
