# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_7/bd_55cd_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_7/bd_55cd_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
