######################################################################
#
# File name : bbpTB_compile.do
# Created on: Mon Dec 06 16:09:17 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../../../../myAd9361.gen/sources_1/ip/bbp_clk_gen" \
"../../../../myAd9361.gen/sources_1/ip/ad9361_fifo/sim/ad9361_fifo.v" \
"../../../../myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen_clk_wiz.v" \
"../../../../myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen.v" \
"../../../../../../../../python_project/bbp_.v" \
"../../../../myAd9361.srcs/sim_1/new/bbpTB.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

