# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/projects/ad9361Test/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_55cd_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_55cd_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
