# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0.xci
# IP: The module: 'system_axi_ddr_cntrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_0/system_axi_ddr_cntrl_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs || ORIG_REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs} -quiet] -quiet

# Block Designs: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/bd_02d8.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8 || ORIG_REF_NAME==bd_02d8} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_0/bd_02d8_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_microblaze_I_0 || ORIG_REF_NAME==bd_02d8_microblaze_I_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_1/bd_02d8_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_rst_0_0 || ORIG_REF_NAME==bd_02d8_rst_0_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_2/bd_02d8_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_ilmb_0 || ORIG_REF_NAME==bd_02d8_ilmb_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_3/bd_02d8_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_dlmb_0 || ORIG_REF_NAME==bd_02d8_dlmb_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_4/bd_02d8_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_dlmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_5/bd_02d8_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_ilmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_6/bd_02d8_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_lmb_bram_I_0 || ORIG_REF_NAME==bd_02d8_lmb_bram_I_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_7/bd_02d8_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_second_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_8/bd_02d8_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_second_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_9/bd_02d8_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_02d8_second_lmb_bram_I_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_10/bd_02d8_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_iomodule_0_0 || ORIG_REF_NAME==bd_02d8_iomodule_0_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_1/system_axi_ddr_cntrl_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0_phy || ORIG_REF_NAME==system_axi_ddr_cntrl_0_phy} -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_0/bd_02d8_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_microblaze_I_0 || ORIG_REF_NAME==bd_02d8_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_0/bd_02d8_microblaze_I_0_ooc_debug.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_1/bd_02d8_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_rst_0_0 || ORIG_REF_NAME==bd_02d8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_1/bd_02d8_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_rst_0_0 || ORIG_REF_NAME==bd_02d8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_2/bd_02d8_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_ilmb_0 || ORIG_REF_NAME==bd_02d8_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_3/bd_02d8_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_dlmb_0 || ORIG_REF_NAME==bd_02d8_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_6/bd_02d8_lmb_bram_I_0_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_9/bd_02d8_second_lmb_bram_I_0_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_10/bd_02d8_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_iomodule_0_0 || ORIG_REF_NAME==bd_02d8_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/bd_02d8_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_0/system_axi_ddr_cntrl_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs || ORIG_REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_0/system_axi_ddr_cntrl_0_microblaze_mcs_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_1/par/system_axi_ddr_cntrl_0_phy_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ddr_cntrl_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/par/system_axi_ddr_cntrl_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ddr_cntrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.srcs/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0.xci
# IP: The module: 'system_axi_ddr_cntrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_0/system_axi_ddr_cntrl_0_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs || ORIG_REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs} -quiet] -quiet

# Block Designs: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/bd_02d8.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8 || ORIG_REF_NAME==bd_02d8} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_0/bd_02d8_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_microblaze_I_0 || ORIG_REF_NAME==bd_02d8_microblaze_I_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_1/bd_02d8_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_rst_0_0 || ORIG_REF_NAME==bd_02d8_rst_0_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_2/bd_02d8_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_ilmb_0 || ORIG_REF_NAME==bd_02d8_ilmb_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_3/bd_02d8_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_dlmb_0 || ORIG_REF_NAME==bd_02d8_dlmb_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_4/bd_02d8_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_dlmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_5/bd_02d8_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_ilmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_6/bd_02d8_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_lmb_bram_I_0 || ORIG_REF_NAME==bd_02d8_lmb_bram_I_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_7/bd_02d8_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_second_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_8/bd_02d8_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_02d8_second_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_9/bd_02d8_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_02d8_second_lmb_bram_I_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_10/bd_02d8_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_02d8_iomodule_0_0 || ORIG_REF_NAME==bd_02d8_iomodule_0_0} -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_1/system_axi_ddr_cntrl_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0_phy || ORIG_REF_NAME==system_axi_ddr_cntrl_0_phy} -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_0/bd_02d8_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_microblaze_I_0 || ORIG_REF_NAME==bd_02d8_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_0/bd_02d8_microblaze_I_0_ooc_debug.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_1/bd_02d8_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_rst_0_0 || ORIG_REF_NAME==bd_02d8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_1/bd_02d8_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_rst_0_0 || ORIG_REF_NAME==bd_02d8_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_2/bd_02d8_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_ilmb_0 || ORIG_REF_NAME==bd_02d8_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_3/bd_02d8_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_dlmb_0 || ORIG_REF_NAME==bd_02d8_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_6/bd_02d8_lmb_bram_I_0_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_9/bd_02d8_second_lmb_bram_I_0_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/ip/ip_10/bd_02d8_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02d8_iomodule_0_0 || ORIG_REF_NAME==bd_02d8_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/bd_0/bd_02d8_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_0/system_axi_ddr_cntrl_0_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs || ORIG_REF_NAME==system_axi_ddr_cntrl_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_0/system_axi_ddr_cntrl_0_microblaze_mcs_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/ip_1/par/system_axi_ddr_cntrl_0_phy_ooc.xdc

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/system_axi_ddr_cntrl_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ddr_cntrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_axi_ddr_cntrl_0/par/system_axi_ddr_cntrl_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ddr_cntrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
