# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.srcs/sources_1/ip/bbp_clk_gen/bbp_clk_gen.xci
# IP: The module: 'bbp_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbp_clk_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbp_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbp_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.srcs/sources_1/ip/bbp_clk_gen/bbp_clk_gen.xci
# IP: The module: 'bbp_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbp_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbp_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/myAd9361/myAd9361.gen/sources_1/ip/bbp_clk_gen/bbp_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbp_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
