# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.srcs/sources_1/bd/system/ip/system_util_ad9361_divclk_0/system_util_ad9361_divclk_0.xci
# IP: The module: 'system_util_ad9361_divclk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/system_util_ad9361_divclk_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ad9361_divclk_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/util_clkdiv_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ad9361_divclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.srcs/sources_1/bd/system/ip/system_util_ad9361_divclk_0/system_util_ad9361_divclk_0.xci
# IP: The module: 'system_util_ad9361_divclk_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/system_util_ad9361_divclk_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ad9361_divclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/adi_hdl/projects/fmcomms2/kcu105/fmcomms2_kcu105.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/util_clkdiv_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ad9361_divclk_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
